apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch-app.yaml
  - patch-ingress.yaml
  - patch-configmap.yaml
  - patch-externalsecret.yaml
  - patch-quota.yaml
  - patch-ollama.yaml
