apiVersion: v1
kind: ResourceQuota
metadata:
  name: navosec-hard-quota
  namespace: navosec-prod
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "10"
    pods: "70"
