apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-cli
  labels:
    external-secrets.io/type: webhook
type: Opaque
stringData:
  # Public URL deines Vaultwarden
  BW_HOST: https://vault.example.com

  # Login-Methode A (empfohlen): API Key + Password zum Unlock
  BW_CLIENTID: CHANGE_ME
  BW_CLIENTSECRET: CHANGE_ME
  BW_PASSWORD: CHANGE_ME

  # Login-Methode B (alternativ): User + Password
  BW_USERNAME: CHANGE_ME
  # BW_PASSWORD wird oben wiederverwendet
