apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navosec-admin-secret
  namespace: navosec-admin
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: navosec-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: ConnectionStrings__DefaultConnection
      remoteRef:
        # Item-ID in Vaultwarden fuer die Admin-DB
        key: CHANGE_ME_ITEM_ID_ADMIN
        property: connection-string
    - secretKey: ConnectionStrings__Redis
      remoteRef:
        key: CHANGE_ME_ITEM_ID_ADMIN
        property: redis-connection
    - secretKey: Auth__Google__ClientId
      remoteRef:
        key: CHANGE_ME_ITEM_ID_ADMIN
        property: google-client-id
    - secretKey: Auth__Google__ClientSecret
      remoteRef:
        key: CHANGE_ME_ITEM_ID_ADMIN
        property: google-client-secret
